apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo-namespace
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: demo-image
        command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          protocol: TCP
          name: app-port