api-name: config-management
namespace: config-management-namespace
port: 8000
version: v1
endpoints:
  - /configs:
      GET: developer
      POST: developer
  - /configs/*:
      GET: NO_AUTHENTICATION
      PUT: NO_AUTHENTICATION
      DELETE: NO_AUTHENTICATION