apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: database-namespace
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: database-port
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_DB
              value: "auth_db"

          volumeMounts:
            - name: postgres-init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-init-scripts
          configMap:
            name: postgresql
