apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: database-namespace
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: database-port
  type: ClusterIP
